exp_name: '[NSGA2-{}]'

algorithm:
  name: nsga2
  kwargs:
    pop_size: 50
    n_offsprings: 50

operators:
  sampling:
    name: int_random
    kwargs: {}

  crossover:
    name: int_ux
    kwargs:
      prob: .9
    
  mutation:
    name: int_pm
    kwargs:
      prob: .2
  
eliminate_duplicates:
  name:
  kwargs:

problem:
  name: problem.{}EfficiencyAccuracyNATS
  kwargs:
    search_space: 
    dataset: 
    epoch: 24
    efficiency: 

    pf_path: data/bench_pf/[{dataset}-{search_space}][{efficiency}-test_err]-{hp}EP.npy
    pf_dict:
      dataset:

termination:
  name: n_eval
  kwargs:
    n_max_evals: 3000